platform :ios, '9.0'
use_frameworks!

target 'SwiftReactNativeHybrid' do

  # Pods for SwiftReactNativeHybrid
  # Required due to https://github.com/facebook/react-native/issues/11781
  react_path = '../node_modules/react-native'
  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket', # needed for debugging
    'RCTLinkingIOS',
    'BatchedBridge',
    'DevSupport'
  ]
  yoga_path = File.join(react_path, 'ReactCommon/yoga')
  pod 'Yoga', :path => yoga_path

  target 'SwiftReactNativeHybridTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftReactNativeHybridUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
